#!/bin/bash

printf "Generating Default Directories\n"
if [ ! -d ~/Documents ]; then
   mkdir ~/Documents
fi
if [ ! -d ~/Downloads ]; then
    mkdir ~/Downloads
fi
if [ ! -d ~/Downloads ]; then
    mkdir ~/Media
fi

os=${OSTYPE//[0-9.-]*/}
case "$os" in
    darwin)
        ./.dotfile_scripts/mac_setup
        ./.dotfile_scripts/backup_dotfiles
        ;;
    msys)
        printf "Windows not supported\n"
        ;;
    linux)
distro=$(cat /etc/*-release | grep ID_LIKE= | sed "s/ID_LIKE=//")
        case $distro in
            debian)
                ./.dotfile_scripts/linux_debian_installs        
                ;;
            *)
                printf "Unknown distro $distro\n"
                exit 1
                ;;
        esac
        ./.dotfile_scripts/backup_dotfiles
        ./.dotfile_scripts/linux_setup
        ;;
    *)
        printf "Unknown OS $OSTYPE\n"
        exit 1
        ;;
esac

exit
shell=${SHELL/\/bin\//.}
case $shell in
    bash)
        source ~/.bashrc
        ;;
    zsh)
        source $HOME/.zshrc
        ;;
    *)
    printf "Unknown shell $SHELL\n"
esac

printf "Cleaning Up extra folders/files\n"
rm -rf starter 
rm install 
rm -rf .dotfile_scripts/linux* 
rm -rf .dotfile_scripts/mac*

printf "Finished dotfile transfer and environment setup\n"

printf "
                       -------------------
                       srepollock Dotfiles
                       -------------------
"

