#!/bin/bash

printf "Generating Default Directories\n"
if [ ! -d ~/Documents ]; then
   mkdir ~/Documents
fi
if [ ! -d ~/Downloads ]; then
    mkdir ~/Downloads
fi
if [ ! -d ~/Downloads ]; then
    mkdir ~/Media
fi

os=${OSTYPE//[0-9.-]*/}
case "$os" in
    darwin)
        ./.dotfile_scripts/macos_install
        ./.dotfile_scripts/backup_dotfiles
        ./.dotfile_scripts/macos_setup
        for f in $(find ./scripts/ -maxdepth 1 -type d); do
            filename=$(basename $f)
            sudo ln -s $PWD/scripts/$filename /usr/local/bin/$filename 
        done
        ;;
    msys)
        printf "Windows not supported\n"
        ;;
    linux)
distro=$(cat /etc/os-release | grep -E "ID=[a-zA-Z]" | sed "s/ID=//")
        case $distro in
            debian)
                ./.dotfile_scripts/linux/linux_debian_installs        
                ;;
            ubuntu)
                ./.dotfile_scripts/linux/linux_debian_installs
                ;;
            alpine)
                ./.dotfile_scripts/linux/linux_debian_installs
                ;;
            *)
                printf "Unknown distro $distro\n"
                exit 1
                ;;
        esac
        ./.dotfile_scripts/backup_dotfiles
        ./.dotfile_scripts/linux/linux_setup
        for f in $(find ./scripts/ -maxdepth 1 -type d); do
            filename=$(basename $f)
            sudo ln -s $PWD/scripts/$filename /usr/local/bin/$filename 
        done
        ;;
    *)
        printf "Unknown OS $OSTYPE\n"
        exit 1
        ;;
esac

chsh -s /bin/zsh

shell=${SHELL/\/bin\//.}
case $shell in
    bash)
        source $HOME/.bashrc
        ;;
    zsh)
        source $HOME/.zshrc
        ;;
    *)
    printf "Unknown shell $SHELL\n"
esac

printf "Cleaning Up extra folders/files\n"
rm -rf starter 
rm -rf .dotfile_scripts/linux* 
rm -rf .dotfile_scripts/mac*

printf "Finished dotfile transfer and environment setup\n"

printf "
                       -------------------
                       srepollock Dotfiles
                       -------------------
"

rm install 
