#!/usr/bin/env python
'''
A simple configuration file to run at the beginning of install.

This can have flags to backup the original files, just incase something goes wrong with the install.

This can also set environment variables
'''
import argparse
import curses
import errno
import logging
import progressbar
import re
import shlex
import shutil
import subprocess
import sys
import time
import os
from os.path import expanduser
'''
Global Variables
'''
DEBUG = False
VERBOSE = False
'''
Classes and Functions
'''
class VersionAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        version = self.get_version()
        setattr(namespace, self.dest, version)
    def run_git_command(self, command): 
        '''
        Runs the git command via subprocess. Command is split by shlex.

        Returns true or false for completion.
        '''
        global DEBUG
        if not DEBUG:
            logging.info('Running run_git_command')
            process = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE)
            (data, err) = process.communicate()
            if (err):
                raise Exception()
                return False
            else:
                logging.info('Completed running command: \'{}\''.format(command))
        else:
            logging.debug('run_git_command hit but not run. Command would have been: {}'.format(command))
            return False
        return True
    def get_version(self):
        version = '0.0.0'
        # TODO: Get the version number based on the latest tag. if none found, version 0.0.0
        return version
class BackupLocationAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        backup_location = os.path.dirname(os.path.realpath(sys.argv[0]))
        setattr(namespace, self.dest, backup_location)
class FileLocationAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        file_location = expanduser('~')
        setattr(namespace, self.dest, file_location)
def copy_anything(src, dst):
    '''
    Copies any types of files or directories (recursively) from src -> dest.

    Returns nothing
    '''
    try:
        shutil.copytree(src, dst)
    except OSError as exc: # python >2.5
        if exc.errno == errno.ENOTDIR:
            shutil.copy(src, dst)
        else: raise
def backup_files(file_location_from, backup_location_to):
    '''
    Backup Files
    
    Creates a new directory at the file_location_from (returned).
    Copies 'the files' (see regex) to the new 'backup' location.
    Prints when done.

    Returns the backup location.
    '''
    global DEBUG
    backup = os.path.join(backup_location_to, '.dotfile_backup')
    log('Backup location: {}'.format(backup), message_type='verbose')
    if not (os.path.exists(backup)):
        os.makedirs(backup)
    else: # start fresh
        shutil.rmtree(backup)
        os.makedirs(backup)
    progress = 0
    with progressbar.ProgressBar(len(os.listdir(file_location_from))) as bar:
        for filename in os.listdir(file_location_from):
            if (re.match('(^\.)(bashrc|bash_profile|npmrc|oh-my-zsh|vimrc|vscode|zsh|zprofile)', filename)):
                log('Copying file {} -> {}'.format(os.path.join(file_location_from, filename), os.path.join(backup, filename)))
                if not DEBUG:
                    copy_anything(os.path.join(file_location_from, filename), os.path.join(backup, filename))
            progress += 1
            bar.update(progress)
    log('Finished copying files')
    return backup
def set_environment_variables(environment_dictionary):
    # TODO: Implement
    log('Not yet implemented', message_type='verbose')
    return
def log(message, message_type='info'):
    # TODO: Properly implement a message type as an enum/dictionary/map
    if VERBOSE or message_type == 'verbose':
        print (message)
        logging.info(message)
    if DEBUG or message_type == 'debug':
        print (message)
        logging.debug(message)
    # TODO: Especially this part.
    if not DEBUG and not VERBOSE and not message_type == 'debug' and not message_type == 'verbose':
        logging.info(message)
    return
'''
Main runners
'''
def get_args():
    '''
    Gets the arguments for the user

    Returns the arguments from the user in a Key,Value Namespace.
    '''
    description = '''
    Dotfiles config

    Config to setup the dotfiles installer.

    Created by Spencer Pollock (spencer@spollock.ca)
    '''
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('os', help='Name the operating system you\'re going to be using the dotfiles on.')
    parser.add_argument('-l', '--file_location', dest='file_location', action=FileLocationAction, nargs=0, help='Directory that the files are normally in. This is typically the home directory and shouldn\'t be changed normally.')
    parser.add_argument('-b', '--backup_location', dest='backup_location', action=BackupLocationAction, nargs=0, help='Directory that the files are saved to. This is usually in the \'dotfiles\' directory, but can be changed per user preference')
    parser.add_argument('--debug', dest='debug', action='store_true', help='Runs the script in debug mode where no action is done.') 
    parser.add_argument('--verbose', dest='verbose', action='store_true', help='Runs the script in verbose mode.') 
    parser.add_argument('-v', '--version', dest='version', action=VersionAction, nargs=0, help='Gets the version of the script')
    return parser.parse_args()
def main(args):
    '''
    Main function for running.
    '''
    global DEBUG
    DEBUG = args.debug
    global VERBOSE
    VERBOSE = args.verbose
    if (DEBUG):
        log('DEBUG is {}'.format(DEBUG))
    if (VERBOSE):
        log('Verbose is {}'.format(VERBOSE))
    if (args.version):
        log(args.version, message_type='verbose')
        return
    if (args.os == 'macos' or args.os == 'windows' or args.os == 'linux'): # To be used later
        file_location = backup_files(args.file_location, args.backup_location)
        log('Files have been successfully backed up:', message_type='verbose')
        for filename in os.listdir(file_location):
            log('\t- {}'.format(filename), message_type='verbose')
    else:
        log('No operating system selected. Please choose [macOS/windows/linux] instead.')
    log('Dotfile config has completed', message_type='verbose')
    return 0

if __name__ == "__main__":
    logging.basicConfig(format='%(asctime)s - %(message)s', filename='log.config', level=logging.DEBUG, datefmt='%Y-%m-%d %H:%M:%S')
    args = get_args()
    main(args)
    logging.shutdown()
