#!/bin/bash

PACKAGE_LIST="locales vim rsync wget curl git git-lfs zsh fonts-powerline python python3"

printf "Updating apt\n"
sudo apt update -y 

printf "Installing gnupg, gnupg1, gnupg2\n"
sudo apt install -y gnupg gnupg1 gnupg2

printf "Adding GitHub CLI package repository to apt\n"
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

printf "Installing gpg keys for github cli\n"
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 23F3D4EA75716059

printf "Installing gpg keys for kali cli\n"
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys ED444FF07D8D0BF6

printf "Updating apt\n"
sudo apt update  -y

printf "Upgrade apt\n"
sudo apt upgrade -y

printf "Installing packages for Debian Linux\n"
sudo apt install -y $PACKAGE_LIST

printf "Adding Kali package repository to apt\n"
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" | sudo tee /etc/apt/sources.list
echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list
echo "#deb-src http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list
echo "#deb https://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/ /kali main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/ /wheezy main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/kali kali-dev main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/kali kali-dev main/debian-installer" | sudo tee -a /etc/apt/sources.list
echo "#deb-src http://http.kali.org/kali kali-dev main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/kali kali main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://http.kali.org/kali kali main/debian-installer" | sudo tee -a /etc/apt/sources.list
echo "#deb-src http://http.kali.org/kali kali main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb http://security.kali.org/kali-security kali/updates main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "#deb-src http://security.kali.org/kali-security kali/updates main contrib non-free" | sudo tee -a /etc/apt/sources.list

printf "Installing Kali signature\n"
#wget https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2020.2_all.deb
#sudo dpkg -i kali-archive-keyring_2020.2_all.deb
wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add

printf "Updating apt with kali and signature\n"
sudo apt update 

printf "Upgrade apt with kali and signature\n"
sudo apt upgrade -y

printf "Installing Kali\n"
sudo apt install -y kali-linux-default

printf "Changing shell to zsh\n"
sudo chsh -s /usr/bin/zsh $USER

printf "Updating Locale\n"
LANG="en_US.UTF-8"
locale-gen

printf "Installing oh-my-zsh\n"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

printf "Installing Python2 pip and Python3 pip3\n"
sudo apt install python-pip python3-pip

printf "Installing outrun\n"
pip3 install outrun

printf "Installing gh cli\n"
sudo apt install gh

printf "Installing Docker\n"
sudo apt-get update && sudo apt-get install ca-certificates curl gnupg lsb-release -y && sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
usermod -aG docker $USER

printf "Installing Fonts\n"
./.dotfile_scripts/linux/linux_fonts

