#!/bin/sh

printf "Setting sshd to start on computer boot\n"
line="@reboot /etc/init.d/sshd start" # /etc/init.d/ssh start # for CentOS/RHEL/Fedora Linux
echo "$line" >> /etc/crontab
printf "Copying dotfiles to home for Linux\n"
directory=$(pwd)
rsync -aqz ${directory}/starter/linux/.??* ${HOME}/
printf "Copying script files to home\n"
rsync -aqz ${directory}/scripts ${HOME}/
