#!/bin/bash

fdate=$(date +%Y_%m_%d_%H-%M)
backup_folder=.dotfiles_backup_$fdate

echo $backup_folder >> $HOME/exclude_folders.txt
cat <<'EOF'>> $HOME/exclude_folders.txt
.dotfiles_backup*/
.dotfile_scripts
install
starter
.Trash/
.Trashbin/
.vscode-remote/
.docker/
.cache/
.local/
.dotnet
EOF

echo $EXCLUDE > exclude_folders.txt
printf "Moving current dotfiles to backup folder: ~/${backup_folder}\n"
rsync -ahvz --progress --exclude-from="$HOME/exclude_folders.txt" --include=".[^.]*" $HOME/ $HOME/$backup_folder/
rm exclude_folders.txt