#!/bin/bash

PACKAGE_LIST="locales vim rsync wget curl git zsh fonts-powerline python python3"

printf "Updating apt\n"
sudo apt update 

printf "Upgrade apt\n"
sudo apt upgrade

printf "Installing packages for Debian Linux\n"
sudo apt install -y $PACKAGE_LIST

printf "Updating Locale\n"
LANG="en_US.UTF-8"
locale-gen

printf "Installing oh-my-zsh\n"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

printf "Installing Python2 pip and Python3 pip3\n"
sudo apt install python-pip python3-pip

printf "Installing outrun\n"
pip3 install outrun
