#!/bin/bash

PACKAGE_LIST="locales vim rsync wget curl git zsh fonts-powerline python python3 kali-linux-default"

printf "Adding GitHub CLI package repository to apt\n"
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

printf "Updating apt\n"
sudo apt update 

printf "Upgrade apt\n"
sudo apt upgrade

printf "Installing packages for Debian Linux\n"
sudo apt install -y $PACKAGE_LIST

printf "Updating Locale\n"
LANG="en_US.UTF-8"
locale-gen

printf "Installing oh-my-zsh\n"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

printf "Installing Python2 pip and Python3 pip3\n"
sudo apt install python-pip python3-pip

printf "Installing outrun\n"
pip3 install outrun

printf "Installing gh cli\n"
sudo apt install gh
