#!/bin/sh

source ./backup_dotfiles

printf "Copying dotfiles to home for macOS\n"
#rsync -avq --progress ../starter/macos/ ~/
rsync -aqz starter/macos/.[^.]* ~/

# Install the Solarized Dark theme for iTerm
printf "Install iTerm Theme\n"
open "${HOME}/preferences/SpencerSolarized.itermcolors"

# Install VSCode settings
cp "${HOME}/preferences/vscode-settings.json" "${HOME}/Library/Application Support/Code/User/"
mv "${HOME}/Library/Application Support/Code/User/vscode-settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"