#!/bin/sh

printf "Copying dotfiles to home for macOS\n"
#rsync -avq --progress ../starter/macos/ ~/
directory=$(pwd)
rsync -aqz ${directory}/starter/macos/.??* ${HOME}/

printf "Copying script files to home\n"
rsync -aqz ${directory}/scripts/ ${HOME}/

# Install the Solarized Dark theme for iTerm
printf "Install iTerm Theme\n"
open "${HOME}/preferences/SpencerSolarized.itermcolors"

# Install VSCode settings
cp "${HOME}/preferences/vscode-settings.json" "${HOME}/Library/Application Support/Code/User/"
mv "${HOME}/Library/Application Support/Code/User/vscode-settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
