#!/usr/bin/env python3
# encoding: utf-8
#
#    ^...^ 
#   / o,o \
#   |):::(|
# ====w=w====
# By: Spencer Pollock <spencer at spollock dot ca>
# 

'''
Python Standard Libraries
'''

import argparse
import asyncio
import configparser
import datetime
import glob
import json
import hmac
import hashlib
import logging
import multiprocessing
import random
import re
import shlex
import smtplib
import subprocess
import sys
import threading
import time
import os
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

'''
Libraries
'''
import psutil
from psutil._common import bytes2human
from dotenv import load_dotenv

'''
Local Modules
'''
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'lib')))

'''
Global variables
'''
DEBUG = False
VERBOSE = False

DEFAULT_EMAIL_LIST = ''
TO_EMAIL = None
CC_EMAIL = None
EMAIL_SUBJECT = None
EMAIL_BODY = None

load_dotenv()

'''
Functions
'''
def sys_info():
    status = False
    output = ''
    # gives a single float value
    if (psutil.cpu_percent() > 70):
        # status = True
        logging.log(logging.INFO, "[**] CPU status = True")
    cpu = 'CPU: {}'.format(psutil.cpu_percent())
    output += cpu + '\n'
    logging.log(logging.INFO, cpu)

    if (psutil.virtual_memory().percent > 70):
        status = True
        logging.log(logging.INFO, "[**] MEM status = True")
    mem = 'MEM: {}/{} MB'.format(bytes2human(psutil.virtual_memory().active), bytes2human(psutil.virtual_memory().total))
    output += mem + '\n'
    logging.log(logging.INFO, mem)

    if (psutil.disk_usage('/').percent > 70):
        status = True
        logging.log(logging.INFO, "[**] DSK status = True")
    dsk = 'DSK: total: {}, used {}, free {}'.format(bytes2human(psutil.disk_usage('/')[0]), bytes2human(psutil.disk_usage('/')[1]), bytes2human(psutil.disk_usage('/')[2]))
    output += dsk + '\n'
    logging.log(logging.INFO, dsk)

    return status, output

def google_webhook():
    '''
    Warning The shlex module is only designed for Unix shells.
    The quote() function is not guaranteed to be correct on non-POSIX compliant shells or shells from other operating systems such as Windows. Executing commands quoted by this module on such shells can open up the possibility of a command injection vulnerability.

    Consider using functions that pass command arguments with lists such as subprocess.run() with shell=False.
    '''
    # not_remote_command = 'ssh home {}'.format(shlex.quote(command))
    global EMAIL_BODY
    command = 'curl -0 -v -H \"Content-Type: application/json\" --data \'{}\' \"{}\"'.format(json.dumps({'content': EMAIL_BODY}, indent = 4), os.getenv('DISCORD_WEBHOOK'))
    print (command)
    status, output = subprocess.getstatusoutput(command)
    return status, output

'''
Main runners
'''
def get_args():
    '''
    A good Python example script.
    '''
    parser = argparse.ArgumentParser(description='A fancy description goes here for your script.')
    parser.add_argument('--update', dest='update', action='store_true', help='Sends updates to Google Chat; Used by the root crontab')
    parser.add_argument('--config', dest='configfile', type=str, default='default.cfg', help='Config file to use. Local Global: DEFAULT_CONFIG to \'default.cfg\'.')
    parser.add_argument('--debug', dest='debug', action='store_true', help='Runs debug statements and checks without processing.') # NOTE: to be implemented later
    parser.add_argument('--verbose', dest='verbose', action='store_true', help='Runs the script in verbose mode.') 
    return parser.parse_args()

def main(args):
    '''
    Main function for running.
    '''
    global DEBUG
    global VERBOSE
    global TO_EMAIL
    global CC_EMAIL
    global EMAIL_SUBJECT
    global EMAIL_BODY
    DEBUG = args.debug
    VERBOSE = args.verbose
    if (VERBOSE):
        print ('Verbose is {}'.format(VERBOSE))
        logging.debug('Verbose is {}'.format(VERBOSE))
    if (args.configfile == 'default.cfg'):
        config = configparser.ConfigParser()
        config.read(os.path.abspath(os.path.join(os.path.dirname(__file__), 'default.cfg')))
    else:
        config = configparser.ConfigParser()
        config.read(os.path.abspath(os.path.join(os.path.dirname(__file__), args.configfile)))
    # Start main
    logging.log(logging.INFO, "[**] sys_info started")
    status, output = sys_info()
    TO_EMAIL = config['DEFAULT']['TO_EMAIL']
    CC_EMAIL = config['DEFAULT']['CC_EMAIL']
    EMAIL_SUBJECT = config['DEFAULT']['EMAIL_SUBJECT']
    EMAIL_BODY = config['DEFAULT']['EMAIL_BODY'].format(output)
    if status and not DEBUG:
#        send_email(email_to_list=TO_EMAIL, email_cc_list=CC_EMAIL, email_subject=EMAIL_SUBJECT, email_body=EMAIL_BODY)
        logging.log(logging.INFO, "[**] Status, Output:")
        logging.log(logging.INFO, status)
        logging.log(logging.INFO, output)
    if not DEBUG or args.update:
        status, output = google_webhook()
        logging.log(logging.INFO, "[**] Status, Output:")
        logging.log(logging.INFO, status)
        logging.log(logging.INFO, output)
    logging.log(logging.INFO, "[**] sys_info finished")
    # End main
    return 0

if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s - %(message)s', filename='system_stats.log', level=logging.DEBUG, datefmt='%Y-%m-%d %H:%M:%S')
    args = get_args()
    main(args)
    logging.shutdown()
    sys.exit(0)
    # End of file