#!/usr/bin/env python3
import socket
import sys

def usage():
    print ("Usage: ./tcpclient [url] [port]")
    print ("Example: ./tcpclient www.google.ca 80")
    sys.exit(0)

if len(sys.argv) < 3:
    usage()

target_host = sys.argv[1] 
target_port = int(sys.argv[2])

try:

    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client.connect((target_host, target_port))
    client.send(b"GET / HTTP/1.1\r\nHost: google.com\r\n\r\n")
    response = client.recv(4096)
    print(response.decode())
except Exception as e:
    print (e)