#!/usr/bin/env python3
import socket
import sys
import threading

def usage():
    print ("Usage: ./tcpserver [url] [port]")
    print ("Example: ./tcpserver 0.0.0.0 8000")
    sys.exit(0)

if len(sys.argv) < 3:
    usage()

bind_ip = sys.argv[1] 
bind_port = int(sys.argv[2])

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

server.bind((bind_ip, bind_port))
server.listen(5)

print("[*] Listening on %s:%d" % (bind_ip, bind_port))

def handle_client(client_socket):
    request = client_socket.recv(1024)
    print ("[*] Received: %s" % request)
    client_socket.send(b"ACK!")
    client_socket.close()

while True:
    client,addr = server.accept()
    print("[*] Accepted connection from: %s:%d" %(addr[0], addr[1]))
    client_handler = threading.Thread(target=handle_client, args=(client,))
    client_handler.start()